apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-1
spec:
  running: true
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: fedora-1
    spec:
      storage:
        resources:
          requests:
            storage: 30Gi
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
  template:
    metadata:
      annotations:
        vm.kubevirt.io/os: "rhel9"
      labels:
        kubevirt.io/domain: fedora-1
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 1
          threads: 4
        memory:
          guest: 1Gi
        devices:
          rng: {}
          networkInterfaceMultiqueue: true
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
            model: virtio
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
      terminationGracePeriodSeconds: 180
      accessCredentials:
      - sshPublicKey:
          source:
            secret:
              secretName: ssh-public-key
          propagationMethod:
            configDrive: {}
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: fedora-1
        name: rootdisk
      - cloudInitConfigDrive:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd:
              expire: false
        name: cloudinitdisk